const iranCities = [
  { id: 1, city: "تهران", province: "تهران" },
  { id: 2, city: "مشهد", province: "خراسان رضوی" },
  { id: 3, city: "اصفهان", province: "اصفهان" },
  { id: 4, city: "کرج", province: "البرز" },
  { id: 5, city: "تبریز", province: "آذربایجان شرقی" },
  { id: 6, city: "شیراز", province: "فارس" },
  { id: 7, city: "اهواز", province: "خوزستان" },
  { id: 8, city: "قم", province: "قم" },
  { id: 9, city: "کرمانشاه", province: "کرمانشاه" },
  { id: 10, city: "ارومیه", province: "آذربایجان غربی" },
  { id: 11, city: "رشت", province: "گیلان" },
  { id: 12, city: "زاهدان", province: "سیستان و بلوچستان" },
  { id: 13, city: "همدان", province: "همدان" },
  { id: 14, city: "کرمان", province: "کرمان" },
  { id: 15, city: "یزد", province: "یزد" },
  { id: 16, city: "اردبیل", province: "اردبیل" },
  { id: 17, city: "بندرعباس", province: "هرمزگان" },
  { id: 18, city: "اراک", province: "مرکزی" },
  { id: 19, city: "اسلام‌آباد غرب", province: "کرمانشاه" },
  { id: 20, city: "سنندج", province: "کردستان" },
  { id: 21, city: "گرگان", province: "گلستان" },
  { id: 22, city: "ساری", province: "مازندران" },
  { id: 23, city: "بوشهر", province: "بوشهر" },
  { id: 24, city: "بیرجند", province: "خراسان جنوبی" },
  { id: 25, city: "ایلام", province: "ایلام" },
  { id: 26, city: "خرم‌آباد", province: "لرستان" },
  { id: 27, city: "شهرکرد", province: "چهارمحال و بختیاری" },
  { id: 28, city: "یاسوج", province: "کهگیلویه و بویراحمد" },
  { id: 29, city: "زنجان", province: "زنجان" },
  { id: 30, city: "قزوین", province: "قزوین" },
];

export { iranCities };
